In [1]:
import numpy as py
import matplotlib as plot
import pandas as pd



In [3]:
dataset = pd.read_csv('Data.csv')

In [60]:
matrixOfFeature = dataset.iloc[:, :-1].values # extract all the columns except the last

In [13]:
dependentVariableVector = dataset.iloc[:, 3].values

In [25]:
dependentVariableVector

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [19]:
from sklearn.preprocessing import Imputer 

In [20]:
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)

In [61]:
imputer = imputer.fit(matrixOfFeature[:, 1:3])

In [62]:
matrixOfFeature[:, 1:3] = imputer.transform(matrixOfFeature[:, 1:3])

In [63]:
matrixOfFeature

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [46]:
from sklearn.preprocessing import LabelEncoder

In [47]:
lableEncoder = LabelEncoder() # encoded the country names into a number

In [64]:
encodedValuesOfCountry = lableEncoder.fit_transform(matrixOfFeature[:, 0])

In [65]:
matrixOfFeature[:, 0] = encodedValuesOfCountry

In [66]:
matrixOfFeature # now the column 0 should be dummy encoded since these numbers should not be compared naturally

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [51]:
from sklearn.preprocessing import OneHotEncoder

In [69]:
oneHotEncoder = OneHotEncoder(categorical_features=[0])

In [70]:
matrixOfFeature = oneHotEncoder.fit_transform(matrixOfFeature).toarray()

/home/nive/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [71]:
matrixOfFeature

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.40000000e+01, 7.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        2.70000000e+01, 4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        3.00000000e+01, 5.40000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        3.80000000e+01, 6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        4.00000000e+01, 6.37777778e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.50000000e+01, 5.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        3.87777778e+01, 5.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.80000000e+01, 7.90000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        5.00000000e+01, 

In [72]:
lableEncoderOfDepVar = LabelEncoder()

In [77]:
 dependentVariableVectorEncoded = lableEncoderOfDepVar.fit_transform(dependentVariableVector)

In [78]:
dependentVariableVectorEncoded # now the data is ready for spliting

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [79]:
# define vars for training and test sets, assume matrix of feature is X and dependent variable is y e.g y = an equation of x

In [81]:
from sklearn.model_selection import train_test_split

In [82]:
x_train, x_test, y_train, y_test = train_test_split(matrixOfFeature, dependentVariableVectorEncoded, test_size = 0.2, random_state =0)

In [87]:
from sklearn.preprocessing import StandardScaler

In [88]:
scaler_x = StandardScaler()

In [89]:
x_train = scaler_x.fit_transform(x_train)

In [90]:
x_test = scaler_x.transform(x_test)

In [93]:
x_train

array([[ 1.        , -1.        ,  2.64575131, -0.77459667,  0.26306757,
         0.12381479],
       [-1.        ,  1.        , -0.37796447, -0.77459667, -0.25350148,
         0.46175632],
       [ 1.        , -1.        , -0.37796447,  1.29099445, -1.97539832,
        -1.53093341],
       [ 1.        , -1.        , -0.37796447,  1.29099445,  0.05261351,
        -1.11141978],
       [-1.        ,  1.        , -0.37796447, -0.77459667,  1.64058505,
         1.7202972 ],
       [ 1.        , -1.        , -0.37796447,  1.29099445, -0.0813118 ,
        -0.16751412],
       [-1.        ,  1.        , -0.37796447, -0.77459667,  0.95182631,
         0.98614835],
       [-1.        ,  1.        , -0.37796447, -0.77459667, -0.59788085,
        -0.48214934]])

In [95]:
%%writefile test.py

UsageError: %%writefile is a cell magic, but the cell body is empty.
